language: minimal
os: linux
dist: focal
group: edge

env:
  global:
  # for updates check developer.android.com/studio#downloads (current 26.1.1)
  - ANDROID_SDK_TOOLS=commandlinetools-linux-7302050_latest.zip

#language: android
#jdk: oraclejdk8
#
#android:
#  licenses:
#    - 'android-sdk-preview-license-.+'
#    - 'android-sdk-license-.+'
#    - 'google-gdk-license-.+'
# 
#  components:
#    - tools
#    - build-tools-30.0.2
#    - android-30
#    #- android-22
#    #- extra-google-google_play_services
#    #- extra-google-m2repository
#    #- extra-android-m2repository
#    #- sys-img-armeabi-v7a-android-22
 
#before_install:
#  #- chmod +x gradlew
#  - yes | sdkmanager "platforms;android-30"

before_script:
 #- echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
 # - emulator -avd test -no-audio -no-window &
 # - android-wait-for-emulator
 # - adb shell input keyevent 82 &
 # - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt-get install openjdk-11-jdk
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
  - mv $HOME/sdk/cmdline-tools $HOME/sdk/latest
  - mkdir $HOME/sdk/cmdline-tools
  - mv $HOME/sdk/latest $HOME/sdk/cmdline-tools/
  - export PATH=$PATH:$HOME/sdk/cmdline-tools/latest/bin
  - export ANDROID_SDK_ROOT=$HOME/sdk
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-29"
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "emulator" "tools" "platform-tools"
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
  - yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "build-tools;29.0.3"
  # not nice but well.. 
  - npm config set strict-ssl false
  - sudo npm install -g cordova
  - cordova platfrom add android

script:
  - cordova build
  #- ./gradlew clean build
  #- ./gradlew test
  #- ./gradlew build check


